name: Run Python Tests and Check Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest # Dùng Windows để build .exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests pyinstaller

      - name: Run hello.py
        run: python hello.py

      - name: Run hi.py and print output
        run: |
          python -c "from hi import say_hi; print(say_hi('Grok'))"

      - name: Run tests
        run: pytest test_hi.py --verbose

      - name: Build hi.py into .exe
        run: pyinstaller --onefile hi.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hi-executable
          path: dist/hi.exe

      - name: Check personal server
        run: |
          curl -s -o /dev/null -w "%{http_code}" ${{ secrets.SERVER_URL }}
          if [ $? -eq 0 ]; then
            echo "Server is up and running!"
          else
            echo "Failed to reach server"
            exit 1
          fi