name: Run Python Tests and Outputs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run hello.py
        run: python hello.py

      - name: Run hi.py and print output
        run: |
          python -c "from hi import say_hi; print(say_hi('Grok'))"

      - name: Run tests
        run: pytest test_hi.py