name: Check Python Syntax

# Khi nào workflow chạy: mỗi lần push hoặc pull request vào nhánh main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Các bước thực thi
jobs:
  syntax-check:
    runs-on: ubuntu-latest # Máy ảo do GitHub cung cấp
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Lấy mã nguồn từ repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Dùng Python 3.x

      - name: Check syntax
        run: python -m py_compile hello.py # Kiểm tra cú pháp file Python